見た目がヤバいなという感じだった部分を直した
twin-te/twinte-landing-page pull request #36
Opened 2020-12-21 17:16 UTC by KanadeNishizawa

# やったこと
見た目があまりにもヤバいなという感じだった部分を直した。
- Twin:teとは？の説明用の画像の素材を作り直して差し替えた
- 不要そうな装飾を削除した(Q&Aの吹き出しとか特徴欄のbackground-colorとか)
- paddingやmarginのremで良さそうな部分を置き換えた
- 画面によって大きすぎたりしてしまっていた要素を直した

|after|before|
|---|---|
|![](https://user-images.githubusercontent.com/48097323/102803191-3cbfff00-43fb-11eb-9389-cd24b3e5b776.png)|![](https://user-images.githubusercontent.com/48097323/102803250-53feec80-43fb-11eb-87bd-84ddfb59f29f.png)
|![](https://user-images.githubusercontent.com/48097323/102801309-64619800-43f8-11eb-9745-31bf63ab13aa.png)|![](https://user-images.githubusercontent.com/48097323/102803125-1c904000-43fb-11eb-8d1f-94a8b187685e.png)|

気になった部分を取り急ぎやったので、提供してもらった大学の画像に差し替えたりとかその他もう少し時間がかかりそうな修正事項は後日別commitでやります。

# 確認したこと
- [X] 動く

# 備考
今回は単なる微修正なので、以前やると言っていたlanding pageの刷新ではないです。
次verのTwin:teリリースにあたってLP自体は新しく作り替えなくてはいけなくなるので、vueへの移行とか大幅なデザインの変更はこのLPではもうやらなくて良いかなという気持ちです。次のLPではちゃんとしたいです。

2020-12-22 00:17 UTC, HikaruEgashira requested changes
コラ画像のサイズが大きいのとかも気になったけどそれはオッケーにしとく！
browserslist使ったのはどこ情報ですか？

2020-12-22 00:17 UTC, HikaruEgashira commented on package.json
> +    "ie 9",
ieは切りたいです。重くなるだけ無駄なので

2020-12-22 00:17 UTC, HikaruEgashira commented on src/index.html
> +        <div class="title-wrap ">
フォーマットできてない感

2020-12-22 02:00 UTC, KanadeNishizawa commented on package.json
> +    "ie 9",
かわいそうに。。。

2020-12-22 02:15 UTC, KanadeNishizawa commented
> コラ画像のサイズが大きいのとかも気になったけどそれはオッケーにしとく！
> browserslist使ったのはどこ情報ですか？

押忍、直した
yarn start時にUnknown versionでerrorになったブラウザを片っ端から消してました・・・。
これ→ https://github.com/parcel-bundler/parcel/issues/5164

2020-12-22 03:00 UTC, KanadeNishizawa commented
> コラ画像のサイズが大きいのとかも気になったけどそれはオッケーにしとく！

画像サイズが大きいのはただの圧縮忘れでしたわ・・・
直しといた

2020-12-26 02:45 UTC, HikaruEgashira approved these changes
:good_higero:

2020-12-26 10:27 UTC, merged