Add footer
twin-te/twinte-landing-page pull request #49
Opened 2021-03-31 15:05 UTC by hayato24s

footer部分を追加しました。

2021-03-31 19:08 UTC, KanadeNishizawa requested changes
2点だけお願いします!

2021-03-31 19:08 UTC, KanadeNishizawa commented on src/organisms/Footer.vue
> +    <div class="footer__email">email: info@twinte.net</div>
`mailto:~`のhrefを設定してください!

2021-03-31 19:08 UTC, KanadeNishizawa commented on src/organisms/Footer.vue
> +    grid-area: links;
```suggestion
    grid-area: links;
    font-weight:400
```

2021-04-01 04:09 UTC, hayato24s commented
ついでに以下の2点も修正しておきました。
- 未訪問時のリンクのカラー
- ヘッダーのwidth

2021-04-01 07:15 UTC, KanadeNishizawa approved these changes
あざます!

2021-04-01 07:16 UTC, merged