composition-apiに修正
twin-te/twinte-landing-page pull request #53
Opened 2021-04-01 09:26 UTC by hayato24s

sponsorが動かなくなっていたのを修正しました。
アニメーション関連は何も手をつけていません。

2021-04-01 12:05 UTC, SIY1121 commented
新APIの対応まではやってない感じかな？

2021-04-02 08:49 UTC, HikaruEgashira requested changes

2021-04-02 08:49 UTC, HikaruEgashira commented on src/pages/Sponsor.vue
> +      });
method not implementsって出るけどこっちで
```suggestion
    const baseUrl = "https://app.twinte.net/api/v3";
    fetch(`${baseUrl}/donation/aggregate/totalAmount`)
      .then((res) => res.json())
      .then((data) => {
        amount.value = data.total;
      });
    fetch(`${baseUrl}/donation/aggregate/users`)
      .then((res) => res.json())
      .then((data) => {
        users.value = data;
        count.value = data.length;
      });
```

2021-04-02 09:14 UTC, takonasu reviewed
とりあえず、URLが正しくなかったのでここだけ
他の部分は時間がなくて見れなかったので他の人レビューお願いします

2021-04-02 09:14 UTC, takonasu commented on src/pages/Sponsor.vue
> +    fetch("https://api.twinte.net/v3/donation/aggregate/users")
https://app.twinte.net/api/v3/donation/aggregate/users

2021-04-02 09:14 UTC, takonasu commented on src/pages/Sponsor.vue
> +    fetch("https://api.twinte.net/v3/donation/aggregate/totalAmount")
https://app.twinte.net/api/v3/donation/aggregate/totalAmount

2021-04-02 10:23 UTC, SIY1121 requested changes
デザインが崩れてるので修正お願いします 🙏 
![image](https://user-images.githubusercontent.com/17082836/113407652-b5662c80-93e8-11eb-9d88-718ab2b67e02.png)

2021-04-02 10:24 UTC, SIY1121 commented
たこなすが書いてくれてますがurlの変更もお願いします

2021-04-02 12:02 UTC, KanadeNishizawa commented
@SIY1121 (@takonasu) url込みで修正しました、大丈夫そうでしょうか？

2021-04-02 12:10 UTC, SIY1121 approved these changes
動作確認しました！
お疲れさまでした 🙏

2021-04-02 12:12 UTC, HikaruEgashira commented
gg

2021-04-02 12:18 UTC, KanadeNishizawa commented
代理します:pray:

2021-04-02 12:21 UTC, merged